from setuptools import setup, find_packages

setup(
    name="agentx",
    version="0.1.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "click>=8.0.0",
        "pyyaml>=6.0.0",
        "langchain>=0.1.0",
        "langchain-google-genai>=0.0.5",
        "langgraph>=0.0.26",
        "langmem>=0.1.0",
        "playwright>=1.40.0",
        "prometheus-client>=0.19.0",
        "redis>=4.5.0",
        "chromadb>=0.4.0",
        "google-cloud-aiplatform>=1.36.4",
        "google-generativeai>=0.3.2",
        "PyGithub>=2.1.0",
        "htmlhint>=0.1.0",
        "lighthouse>=0.1.0",
        "hint>=0.1.0",
    ],
    entry_points={
        "console_scripts": [
            "agentx=agentx.cli:cli",
        ],
    },
    author="Your Name",
    author_email="your.email@example.com",
    description="Autonomous Website Maintenance Framework",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/agentx",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.9",
) 